local.run=false

# ---------------------------- Integration
orchestrator.uri=http://localhost:8080/

# ---------------------------- Holder
s3.access.key.id=
s3.secret.access.key=
client.region=endpoint
connection.ssl.enabled=true
impl.disable.cache=true
s3.path.style.access=true
s3.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
s3.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider


# ---------------------------- S3
hive.metastore.local=false
#For local
#hive.metastore.uris=thrift://hive-metastore.hive-metastore.k8s.data-transfer-dev-1.salt.x5.ru:9083
hive.metastore.uris=thrift://hive-metastore.hive-metastore:9083
#fs.s3a.access.key=0099895b2ec8a45dd86c
#fs.s3a.secret.key=UOSKtdnllj1WhocT61B5xj1SJism4E4uj159XHWk
fs.s3a.access.key=
fs.s3a.secret.key=
fs.s3a.connection.ssl.enabled=true
fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
fs.s3a.path.style.access=true
#fs.s3a.endpoint=https://s3-endpoint.sss-msk1.x5.ru
fs.s3a.endpoint=https://s3-endpoint.sss2-msk2.x5.ru
fs.s3a.region=endpoint
io-impl=org.apache.iceberg.aws.s3.S3FileIO
s3.path-style-access=true
#s3.endpoint=https://s3-endpoint.sss-msk1.x5.ru
s3.endpoint=https://s3-endpoint.sss2-msk2.x5.ru
warehouse=s3a://datatransfer


# ---------------------------- KAFKA
bootstrap.servers=mn-etlkfk01.x5.ru:9092,mn-etlkfk02.x5.ru:9092,mn-etlkfk03.x5.ru:9092
#bootstrap.servers=mn-etlkfk01:9092,mn-etlkfk02:9092,mn-etlkfk03:9092
topic.name=002_019_00001
# If keytab is stored in resources, set prefix 'classpath:' here, or set full file path
keytab.location=/opt/bitnami/flink/data_stream4.keytab
keytab.principal=srv.data_stream@X5.RU
